server:
  port: 9092

spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://${my.ip}:23306/tinkerplay?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&connectionTimeout=60000&socketTimeout=60000
          username: root
          password: ENC(dcIi+uEmTIuWfrJ1vpbk5sadABUbXpMz)
          type: com.alibaba.druid.pool.DruidDataSource
        slave_1:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://${my.ip}:13306/tinkerplay?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&connectionTimeout=60000&socketTimeout=60000
          username: root
          password: ENC(dcIi+uEmTIuWfrJ1vpbk5sadABUbXpMz)
          type: com.alibaba.druid.pool.DruidDataSource
      druid:
        initial-size: 5
        max-active: 20
        max-wait: 60000
        min-evictable-idle-time-millis: 300000
        min-idle: 5
        pool-prepared-statements: false
        test-on-borrow: false
        test-on-return: false
        time-between-eviction-runs-millis: 60000
  flyway:
    dataSourceArr: master,slave_1
  servlet:
    multipart:
      location: /Users/yuxinbai/aiyuns/Test/Temp
  data:
    redis:
      port: 16380
      host: ${my.ip}
  rabbitmq:
    addresses: ${my.ip}
    port: 25672
  elasticsearch:
    rest:
      uris: http://${my.ip}:19200
  cloud:
    nacos:
      discovery:
        server-addr: ${my.ip}:38848
  kafka:
    bootstrap-servers: ${my.ip}:19093

body:
  encrypt:
    key: iamwalkerencrypt

file-save-path: /Users/yuxinbai/aiyuns/Test/uploadFile/

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    org:
      mybatis: DEBUG

pdf:
  config:
    output: /Users/yuxinbai/aiyuns/uploadFile/pdf/

data:
  elasticsearch:
    cluster-nodes: ${my.ip}:19300

minio:
  endpoint: http://${my.ip}:19095

token:
  TOKEN_SECRET: my-secret-key

nacos:
  config:
    server-addr: ${my.ip}:38848

cdc:
  datasource:
    enabled: true
    hostname: ${my.ip}
    port: 23306
    database: tinkerplay
    tableList: user
    username: root
    password: ENC(dcIi+uEmTIuWfrJ1vpbk5sadABUbXpMz)

timedtask:
  enabled: false

my:
  ip: ${MY_ADDRESS}
  port: ${MY_PORT}